#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile yarn
  (set +f; cd bin && ln -nfs ../node_modules/.bin/vue* .)
}

bootstrap
