#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile yarn
  mkdir -p "$shome/bin"
  ln -nfs "$(yarn exec -s which vue 2>/dev/null || true)" "$shome/bin/"
  ln -nfs "$(yarn exec -s which vuepress 2>/dev/null || true)" "$shome/bin/"
}

bootstrap
