#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile yarn
  local pth_vue="$(yarn exec -s which vue 2>/dev/null || true)"
  mkdir -p "$shome/bin"
  ln -nfs "$pth_vue" "$shome/bin/"
}

bootstrap
