#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if ! type -P vue >/dev/null; then
    return 1
  fi

  if ! type -P vuepress >/dev/null; then
    return 1
  fi
}

main "$@"
