#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_vue="$(vue --version 2>/dev/null || true)"
  local ver_vuepress="$(vuepress --version 2>/dev/null || true)"
  jq -n \
    --arg vue "$ver_vue" \
    --arg vuepress "$ver_vuepress" \
    '{vue: $vue, vuepress: $vuepress}'
}

version "$@"
